// Generated by CoffeeScript 1.6.3
(function() {
  var banner, bannerClosed, bannerImg, sizeBanner;

  bannerImg = $("#post-banner");

  banner = $("div.post.banner");

  bannerClosed = true;

  $(bannerImg).load(function() {
    return sizeBanner($(this), true, true);
  });

  $(window).resize(function() {
    return sizeBanner(bannerImg, bannerClosed, false);
  });

  banner.click(function() {
    if (bannerClosed) {
      banner.animate({
        "height": bannerImg.height()
      }, 200);
      bannerImg.animate({
        "margin-top": 0
      }, 200);
    } else {
      sizeBanner(bannerImg, true, true);
    }
    return bannerClosed = !bannerClosed;
  });

  sizeBanner = function(b, closed, animate) {
    var h;
    if (closed) {
      h = b.height();
      if (animate) {
        banner.animate({
          "height": banner.width() / 5
        }, 200);
        return b.animate({
          "margin-top": -h / 3
        }, 200);
      } else {
        banner.height(banner.width() / 5);
        return b.css("margin-top", -h / 3);
      }
    } else {
      if (animate) {
        return banner.animate({
          "height": bannerImg.height()
        }, 200);
      } else {
        return banner.css("height", bannerImg.height());
      }
    }
  };

}).call(this);
