// Generated by CoffeeScript 1.6.3
(function() {
  var banner, bannerImg, sizeBanner;

  bannerImg = $("#post-banner");

  banner = $("div.post.banner");

  $(bannerImg).load(function() {
    return sizeBanner($(this));
  });

  $(window).resize(function() {
    return sizeBanner(bannerImg);
  });

  sizeBanner = function(b) {
    var h;
    h = b.height();
    banner.height(banner.width() / 5);
    return b.css("margin-top", -h / 3);
  };

}).call(this);
