// Generated by CoffeeScript 1.6.3
(function() {
  var images;

  images = $("#post-container img");

  images.each(function() {
    var width;
    $(this).wrap("<div class='image-box'></div>");
    $(this).parent().append("<div class='caption'>" + ($(this).attr('alt')) + "</div>");
    width = $(this).attr("box-width");
    if (width) {
      return $(this).parent().attr("style", "width:" + width);
    }
  });

}).call(this);
